package delivery

import (
	"bytes"
	"fmt"
	"html/template"

	"dailyread/internal/domain"
)

type Digest struct {
	Subject string
	Text    string
	HTML    string
}

const htmlTemplateStr = `
<!DOCTYPE html>
<html>
<head>
<style>
  body { font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif; line-height: 1.6; color: #1a1a1a; max-width: 680px; margin: 0 auto; padding: 24px; background: #f5f5f5; }
  .header { background: #07070a; color: #f5a524; padding: 20px 24px; border-radius: 12px; margin-bottom: 28px; }
  .header h1 { margin: 0; font-size: 22px; font-weight: 700; }
  .header p { margin: 6px 0 0; font-size: 13px; color: #9a9cab; }
  h2 { font-size: 13px; font-weight: 700; text-transform: uppercase; letter-spacing: .08em; color: #7c6cff; margin: 28px 0 12px; }
  .article { background: #fff; border: 1px solid #e5e5ea; border-radius: 10px; padding: 18px 20px; margin-bottom: 14px; }
  .article-title { font-size: 17px; font-weight: 600; margin-bottom: 4px; }
  .article-title a { color: #1a1a1a; text-decoration: none; }
  .article-title a:hover { color: #f5a524; }
  .slot { display: inline-block; font-size: 11px; font-weight: 600; text-transform: uppercase; letter-spacing: .06em; padding: 2px 8px; border-radius: 20px; background: #f0f0f5; color: #555; margin-bottom: 10px; }
  .summary { font-size: 14px; color: #444; margin-bottom: 10px; line-height: 1.55; }
  .why { font-size: 14px; color: #27ae60; font-style: italic; margin-bottom: 6px; }
  .how { font-size: 13px; color: #7c6cff; }
  .how strong { font-weight: 600; }
  .meta { font-size: 12px; color: #aaa; margin-top: 10px; }
  .telemetry { margin-top: 36px; padding: 14px 18px; background: #fff; border: 1px solid #e5e5ea; border-radius: 10px; font-size: 12px; color: #999; text-align: center; }
  .footer { text-align: center; font-size: 11px; color: #bbb; margin-top: 20px; }
</style>
</head>
<body>
  <div class="header">
    <h1>&#9679; DailyRead Briefing</h1>
    <p>Your personalized research digest — curated and framed for you.</p>
  </div>

  {{range $tag, $articles := .Groups}}
    <h2>{{$tag}}</h2>
    {{range $articles}}
      <div class="article">
        <div class="article-title"><a href="{{.URL}}">{{.Title}}</a></div>
        {{if .Slot}}<span class="slot">{{.Slot}}</span>{{end}}
        <div class="summary">{{.Summary}}</div>
        {{if .Why}}<div class="why">{{.Why}}</div>{{end}}
        {{if .How}}<div class="how"><strong>How to read:</strong> {{.How}}</div>{{end}}
        <div class="meta">Relevance: {{.Relevance}}/10{{if .WordCount}} &middot; ~{{.WordCount}} words{{end}}</div>
      </div>
    {{end}}
  {{end}}

  <div class="telemetry">
    <strong>Run telemetry</strong><br/>
    Tokens: {{.Stats.TokensIn}} in / {{.Stats.TokensOut}} out &nbsp;&middot;&nbsp;
    Est. cost: ${{printf "%.4f" .Stats.Cost}} &nbsp;&middot;&nbsp;
    Web requests: {{.Stats.WebRequests}}
  </div>
  <div class="footer">Generated by DailyRead &mdash; your personal AI news anchor</div>
</body>
</html>
`

const textTemplateStr = `DailyRead Briefing
==================
Your personalized research digest.

{{range $tag, $articles := .Groups}}
=== {{$tag}} ===
{{range $articles}}
{{.Title}}{{if .Slot}} [{{.Slot}}]{{end}}
{{.URL}}
{{.Summary}}
{{if .Why}}Why: {{.Why}}{{end}}
{{if .How}}How: {{.How}}{{end}}
Relevance: {{.Relevance}}/10{{if .WordCount}} | ~{{.WordCount}} words{{end}}

{{end}}{{end}}
--
Tokens: {{.Stats.TokensIn}} in / {{.Stats.TokensOut}} out | Cost: ${{printf "%.4f" .Stats.Cost}} | Requests: {{.Stats.WebRequests}}
Generated by DailyRead — your personal AI news anchor
`

type FormatData struct {
	Groups map[string][]domain.Candidate
	Stats  *domain.PipelineStats
}

func FormatDigest(candidates []domain.Candidate, stats *domain.PipelineStats) (*Digest, error) {
	if len(candidates) == 0 {
		return nil, fmt.Errorf("no candidates to format")
	}

	// Group candidates by interest tag
	groups := make(map[string][]domain.Candidate)
	for _, c := range candidates {
		groups[c.InterestTag] = append(groups[c.InterestTag], c)
	}

	data := FormatData{
		Groups: groups,
		Stats:  stats,
	}

	htmlTmpl, err := template.New("html").Parse(htmlTemplateStr)
	if err != nil {
		return nil, err
	}

	textTmpl, err := template.New("text").Parse(textTemplateStr)
	if err != nil {
		return nil, err
	}

	var htmlBuf bytes.Buffer
	if err := htmlTmpl.Execute(&htmlBuf, data); err != nil {
		return nil, err
	}

	var textBuf bytes.Buffer
	if err := textTmpl.Execute(&textBuf, data); err != nil {
		return nil, err
	}

	return &Digest{
		Subject: "Your Weekly DailyRead Digest",
		Text:    textBuf.String(),
		HTML:    htmlBuf.String(),
	}, nil
}
