package delivery

import (
	"bytes"
	"fmt"
	"html/template"

	"dailyread/internal/domain"
)

type Digest struct {
	Subject string
	Text    string
	HTML    string
}

const htmlTemplateStr = `
<!DOCTYPE html>
<html>
<head>
<style>
  body { font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif; line-height: 1.6; color: #333; max-width: 800px; margin: 0 auto; padding: 20px; }
  h1 { color: #2c3e50; border-bottom: 2px solid #3498db; padding-bottom: 10px; }
  h2 { color: #2980b9; margin-top: 30px; }
  .article { background: #f9f9f9; border-left: 4px solid #3498db; padding: 15px; margin-bottom: 20px; border-radius: 4px; }
  .title { font-size: 18px; font-weight: bold; margin-bottom: 5px; }
  .meta { font-size: 14px; color: #7f8c8d; margin-bottom: 10px; }
  .summary { margin-bottom: 10px; }
  .why { font-style: italic; color: #27ae60; }
  a { color: #3498db; text-decoration: none; }
  a:hover { text-decoration: underline; }
</style>
</head>
<body>
  <h1>Your Weekly DailyRead Digest</h1>
  <p>Here are the top curated articles for you this week, based on your configured interests.</p>
  
  {{range $tag, $articles := .Groups}}
    <h2>{{$tag}}</h2>
    {{range $articles}}
      <div class="article">
        <div class="title"><a href="{{.URL}}">{{.Title}}</a></div>
        <div class="meta">Relevance: {{.Relevance}}/10 | Words: ~{{.WordCount}}</div>
        <div class="summary">{{.Summary}}</div>
        <div class="why"><strong>Why it was selected:</strong> {{.Why}}</div>
      </div>
    {{end}}
  {{end}}
  
  <hr style="margin-top: 40px; border: 0; border-top: 1px solid #eee;" />
  <div style="font-size: 12px; color: #7f8c8d; text-align: center;">
    <strong>Run Telemetry</strong><br/>
    Tokens: {{.Stats.TokensIn}} in / {{.Stats.TokensOut}} out<br/>
    Estimated LLM Cost: ${{(printf "%.4f" .Stats.Cost)}}<br/>
    Web Requests: {{.Stats.WebRequests}}<br/>
  </div>
  
  <p style="margin-top: 20px; font-size: 12px; color: #999; text-align: center;">
    Generated by DailyRead Multi-Agent Engine
  </p>
</body>
</html>
`

const textTemplateStr = `Your Weekly DailyRead Digest
============================
Here are the top curated articles for you this week, based on your configured interests.

{{range $tag, $articles := .Groups}}
### {{$tag}}

{{range $articles}}
* {{.Title}}
  URL: {{.URL}}
  Relevance: {{.Relevance}}/10 | Words: ~{{.WordCount}}
  Summary: {{.Summary}}
  Why: {{.Why}}

{{end}}
{{end}}

--
[Run Telemetry]
Tokens: {{.Stats.TokensIn}} in / {{.Stats.TokensOut}} out
Estimated LLM Cost: ${{(printf "%.4f" .Stats.Cost)}}
Web Requests: {{.Stats.WebRequests}}

--
Generated by DailyRead Multi-Agent Engine
`

type FormatData struct {
	Groups map[string][]domain.Candidate
	Stats  *domain.PipelineStats
}

func FormatDigest(candidates []domain.Candidate, stats *domain.PipelineStats) (*Digest, error) {
	if len(candidates) == 0 {
		return nil, fmt.Errorf("no candidates to format")
	}

	// Group candidates by interest tag
	groups := make(map[string][]domain.Candidate)
	for _, c := range candidates {
		groups[c.InterestTag] = append(groups[c.InterestTag], c)
	}

	data := FormatData{
		Groups: groups,
		Stats:  stats,
	}

	htmlTmpl, err := template.New("html").Parse(htmlTemplateStr)
	if err != nil {
		return nil, err
	}

	textTmpl, err := template.New("text").Parse(textTemplateStr)
	if err != nil {
		return nil, err
	}

	var htmlBuf bytes.Buffer
	if err := htmlTmpl.Execute(&htmlBuf, data); err != nil {
		return nil, err
	}

	var textBuf bytes.Buffer
	if err := textTmpl.Execute(&textBuf, data); err != nil {
		return nil, err
	}

	return &Digest{
		Subject: "Your Weekly DailyRead Digest",
		Text:    textBuf.String(),
		HTML:    htmlBuf.String(),
	}, nil
}
